name: CI
on:
  pull_request:
    branches:
      - v*
      - develop/*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_tags: [ 'stdlib', 'fastjson' ]
        go: [ '1.24', '1.23' ]
    name: "Test [ Go ${{ matrix.go }} / Tags ${{ matrix.go_tags }} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Cache Go modules
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/bazel
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Go stable version
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Install tparse
        run: go install github.com/mfridman/tparse@v0.12.2
      - run: make generate
      - name: make tidy
        run: make tidy
      - name: Test with coverage
        run: make cover-${{ matrix.go_tags }}
      - uses: bazelbuild/setup-bazelisk@v3
      - run: bazel run //:gazelle-update-repos
      - name: Check difference between generation code and commit code
        run: make check_diffs
