# Smoke tests only run on non-master branches. Smoke tests cut
# some corners by running selected tests in parallel (to shave off
# some execution time)
# Once a pull request is merged to master, workflows/ci.yml is run
name: Smoke Tests
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.24', '1.23' ]
    name: "Smoke [ Go ${{ matrix.go }} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Check documentation generator
        run: |
          find . -name '*.md' | xargs env AUTODOC_DRYRUN=1 perl tools/autodoc.pl
      - name: Cache Go modules
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/bazel
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Go stable version
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Install tparse
        run: go install github.com/mfridman/tparse@latest
      - name: Run go generate
        run: go generate ./...
      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Uncommitted changes found:"
            git status --porcelain
            git diff
            exit 1
          fi
      - name: Go mod tidy
        run: go mod tidy
      - name: Run smoke tests
        run: go test -short ./...
      - uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2 # v3.0.0
      - run: bazel build //...

